"""Base class for offensive attack strategies."""

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional

from agentguard.offensive.attack import AttackCase, AttackType, ExpectedBehavior, SafetyClass
from agentguard.offensive.target import AttackTarget


class AttackStrategy(ABC):
    """Abstract base class for modular offensive attack generation strategies."""

    @property
    @abstractmethod
    def strategy_name(self) -> str:
        """Name of the strategy."""
        pass

    @property
    @abstractmethod
    def primary_attack_type(self) -> AttackType:
        """Primary attack type generated by this strategy."""
        pass

    @abstractmethod
    def generate(
        self,
        target: AttackTarget,
        count: int = 5,
        base_intent: str = "Analyze FY2026 public financial data",
    ) -> List[AttackCase]:
        """Generate structured attack cases for the target system."""
        pass
